export const MESSAGE = {
    VALIDATE_EXIST:"Mã nhân viên đã tồn tại.",
    VALIDATE_EMPTY:" không được để trống.",
    TITLE_CLOSEFORM:"Dữ liệu đã bị thay đổi. Bạn có muốn cất không?",
    TITLE_PRE_DELETE:"Bạn có thực sự muốn xóa Nhân viên <",
    TITLE_LAST_DELETE:"> không?",
    TITLE_PRE_EXIST:"Mã nhân viên <",
    TITLE_LAST_EXIST:"> đã tồn tại trong hệ thống, vui lòng kiểm tra lại.",
    CONFIRM_CLOSE_DELETE:"Có",
    CONFIRM_ERROR:"Đóng",
    CONFIRM_EXIST:"Đồng ý",
    STATUS_POPUP_DELETE:"DELETE",
    STATUS_POPUP_CLOSE:"CLOSE",
    STATUS_POPUP_ERROR:"ERROR",
    STATUS_POPUP_EXIST:"EXIST",
    ICON_POPUP_QUESTION:"icon-question",
    ICON_POPUP_WARNING:"icon-warning",
    ICON_POPUP_ERROR:"icon-error",
    PREFIX_EMPLOYEECODE:"MF",
    ERROR_VALUE_CBB:"Vui lòng chọn đúng các Option ở trên",
    DELETE_SUCCESS:"Bạn đã xóa bản ghi thành công",
    UPDATE_SUCCESS:"Bạn đã sửa dữ liệu thành công",
    INSERT_SUCCESS:"Bạn đã thêm mới bản ghi thành công",
    DELETE_FAIL:"Bạn đã xóa bản ghi thành công",
    UPDATE_FAIL:"Bạn đã sửa dữ liệu thành công",
    INSERT_FAIL:"Bạn đã thêm mới bản ghi thành công",
    SUCCESS_TOAST:"success",
    ERROR_TOAST:"error",
    CODE_EXIST:"Mã nhân viên đã tồn tại. Mời bạn nhập lại",
}
export const iconToast = {
        success: 'fas fa-check-circle',
        error: 'fas fa-exclamation-triangle',
        warning: 'fas fa-exclamation-circle',
}